### ISSUE TITLE
Menu links have too little contrast

### ISSUE THREAD

**Issue by jsoref** [jenkinsci/dark-theme-plugin#140]
Jenkins w/ dark:
![jenkins menu](https://user-images.githubusercontent.com/2119212/89585789-802f1d80-d80c-11ea-9a90-4797ce199cd8.png)
For reference, here's
![slack dark theme](https://user-images.githubusercontent.com/2119212/89585881-a785ea80-d80c-11ea-836e-a300c8b16724.png)
for a link:
![jenkins.io](https://user-images.githubusercontent.com/2119212/89585829-91782a00-d80c-11ea-9b56-5622fc7a2223.png)
selected:
![jenkins.io - selected](https://user-images.githubusercontent.com/2119212/89585923-b8cef700-d80c-11ea-98c0-789fa5d99c74.png)
hovered:
![jenkins.io - hovered](https://user-images.githubusercontent.com/2119212/89585951-c3898c00-d80c-11ea-8626-cf7b191628cb.png)

**Comment by VirtualTim** [comment]
I believe this is fixed by #118.

**Comment by jsoref** [comment]
This was filed after that was fixed.
And the drop down menu still looks more or less as in the bug report.

**Comment by mpnico** [comment]
I can confirm, the problem is still here with, at least, latest jenkins LTS
